-- ANALISE DE GIRO DE ESTOQUE (BASE _2)
-- Objetivo: dataset para Power BI com cobertura, giro, risco de ruptura e excesso.
-- Observacao: se sua base tiver nomes de campos diferentes (ex.: QTD_ESTOQUE),
-- ajuste somente no CTE PRODUTOS.
-- CATEGORIA: descrição do grupo (TB_EST_GRUPO.DESCRICAO), igual a estoque_giro_fragment.sql.

WITH
PARAMS AS (
    SELECT
        90 AS DIAS_JANELA_VENDA,      -- janela para calcular venda media dia
        30 AS DIAS_CRITICO,           -- cobertura < 30 dias => Critico
        60 AS DIAS_ALERTA,            -- cobertura < 60 dias => Alerta
        180 AS DIAS_EXCESSO,          -- cobertura >= 180 dias => Excesso
        30 AS DIAS_SEM_VENDA_ALERTA,  -- sem venda >= 30 dias
        0.20 AS FATOR_ESTOQUE_SEG     -- 20% de estoque de seguranca
    FROM RDB$DATABASE
),
PRODUTOS AS (
    SELECT
        P.ID_IDENTIFICADOR,
        E.ID_ESTOQUE,
        TRIM(COALESCE(E.DESCRICAO, '(sem descricao)')) AS ITEM,
        TRIM(COALESCE(P.REFERENCIA, '')) AS REFERENCIA,
        E.ID_GRUPO,
        TRIM(COALESCE(GR.DESCRICAO, '(sem grupo)')) AS NOME_GRUPO,
        P.ID_NIVEL1,
        P.ID_NIVEL2,
        COALESCE(P.QTD_MINIM, 0) AS QTD_MINIMA,
        COALESCE(P.QTD_ATUAL, 0) AS QTD_ESTOQUE_ATUAL
    FROM TB_EST_PRODUTO_2 P
    INNER JOIN TB_EST_IDENTIFICADOR_2 I ON I.ID_IDENTIFICADOR = P.ID_IDENTIFICADOR
    INNER JOIN TB_ESTOQUE_2 E ON E.ID_ESTOQUE = I.ID_ESTOQUE
    LEFT JOIN TB_EST_GRUPO GR ON GR.ID_GRUPO = E.ID_GRUPO
),
VENDAS AS (
    SELECT
        E.ID_ESTOQUE,
        N.DT_SAIDA AS DT_VENDA,
        COALESCE(I.QTD_ITEM, 0) AS QTD_VENDA,
        COALESCE(I.VLR_TOTAL, 0) AS VLR_VENDA,
        COALESCE(I.VLR_CUSTO, 0) AS VLR_CUSTO
    FROM TB_NFV_ITEM_2 I
    INNER JOIN TB_NFVENDA_2 N ON N.ID_NFVENDA = I.ID_NFVENDA
    INNER JOIN TB_EST_IDENTIFICADOR_2 ID ON ID.ID_IDENTIFICADOR = I.ID_IDENTIFICADOR
    INNER JOIN TB_ESTOQUE_2 E ON E.ID_ESTOQUE = ID.ID_ESTOQUE
    CROSS JOIN PARAMS PR
    WHERE N.FIM = 'Finalizado'
      AND N.DT_SAIDA >= CURRENT_DATE - PR.DIAS_JANELA_VENDA
      AND N.DT_SAIDA < CURRENT_DATE
),
VENDAS_AGR AS (
    SELECT
        V.ID_ESTOQUE,
        SUM(V.QTD_VENDA) AS QTD_VENDIDA_PERIODO,
        SUM(V.VLR_VENDA) AS VALOR_VENDAS_PERIODO,
        SUM(V.VLR_CUSTO) AS CMV_ESTIMADO_PERIODO,
        MAX(V.DT_VENDA) AS ULTIMA_VENDA
    FROM VENDAS V
    GROUP BY V.ID_ESTOQUE
),
BASE AS (
    SELECT
        P.ID_IDENTIFICADOR,
        P.ID_ESTOQUE,
        P.ITEM,
        P.REFERENCIA,
        P.ID_GRUPO,
        P.NOME_GRUPO,
        P.ID_NIVEL1,
        P.ID_NIVEL2,
        P.QTD_MINIMA,
        P.QTD_ESTOQUE_ATUAL,
        COALESCE(VA.QTD_VENDIDA_PERIODO, 0) AS QTD_VENDIDA_PERIODO,
        COALESCE(VA.VALOR_VENDAS_PERIODO, 0) AS VALOR_VENDAS_PERIODO,
        COALESCE(VA.CMV_ESTIMADO_PERIODO, 0) AS CMV_ESTIMADO_PERIODO,
        VA.ULTIMA_VENDA
    FROM PRODUTOS P
    LEFT JOIN VENDAS_AGR VA ON VA.ID_ESTOQUE = P.ID_ESTOQUE
)
SELECT
    B.ID_IDENTIFICADOR,
    CAST(B.ID_IDENTIFICADOR AS VARCHAR(50)) AS CODIGO_ITEM,
    B.ITEM,
    B.REFERENCIA,
    B.ID_GRUPO,
    B.NOME_GRUPO AS CATEGORIA,
    B.ID_NIVEL1,
    B.ID_NIVEL2,
    B.QTD_ESTOQUE_ATUAL AS QUANT_ESTOQUE,
    B.QTD_MINIMA AS ESTOQUE_MINIMO_CADASTRO,
    ROUND((B.QTD_ESTOQUE_ATUAL + B.QTD_MINIMA) / 2.0, 2) AS ESTOQUE_MEDIO,
    B.QTD_VENDIDA_PERIODO AS QUANT_VENDAS,
    ROUND(B.VALOR_VENDAS_PERIODO, 2) AS VALOR_VENDAS,
    ROUND(B.CMV_ESTIMADO_PERIODO, 2) AS CMV_ESTIMADO,
    ROUND(B.QTD_ESTOQUE_ATUAL * (B.CMV_ESTIMADO_PERIODO / NULLIF(B.QTD_VENDIDA_PERIODO, 0)), 2) AS VALOR_ESTOQUE_ESTIMADO,
    B.ULTIMA_VENDA,
    CASE
        WHEN B.ULTIMA_VENDA IS NULL THEN 9999
        ELSE CURRENT_DATE - B.ULTIMA_VENDA
    END AS DIAS_SEM_VENDA,
    CASE
        WHEN B.ULTIMA_VENDA IS NULL THEN 9999
        ELSE CURRENT_DATE - B.ULTIMA_VENDA
    END AS "MEDIA DE DIAS SEM VENDA",
    ROUND(B.QTD_VENDIDA_PERIODO / PR.DIAS_JANELA_VENDA, 4) AS VENDA_DIA_MEDIA,
    ROUND(B.QTD_VENDIDA_PERIODO / PR.DIAS_JANELA_VENDA, 4) AS "PROVISAO DE VENDAS POR DIA",
    CASE
        WHEN ((B.QTD_ESTOQUE_ATUAL + B.QTD_MINIMA) / 2.0) > 0
        THEN ROUND(B.QTD_VENDIDA_PERIODO / ((B.QTD_ESTOQUE_ATUAL + B.QTD_MINIMA) / 2.0), 4)
        ELSE NULL
    END AS "GIRO DE ESTOQUE",
    CASE
        WHEN B.QTD_VENDIDA_PERIODO > 0
         AND ((B.QTD_ESTOQUE_ATUAL + B.QTD_MINIMA) / 2.0) > 0
        THEN ROUND(PR.DIAS_JANELA_VENDA /
                   (B.QTD_VENDIDA_PERIODO / ((B.QTD_ESTOQUE_ATUAL + B.QTD_MINIMA) / 2.0)), 2)
        ELSE NULL
    END AS "TEMPO MEDIO DE ESTOQUE",
    CASE
        WHEN B.QTD_VENDIDA_PERIODO > 0
        THEN ROUND(B.QTD_ESTOQUE_ATUAL / (B.QTD_VENDIDA_PERIODO / PR.DIAS_JANELA_VENDA), 2)
        ELSE NULL
    END AS ESTOQUE_EM_DIAS,
    ROUND((B.QTD_VENDIDA_PERIODO / PR.DIAS_JANELA_VENDA) * PR.DIAS_ALERTA * (1 + PR.FATOR_ESTOQUE_SEG), 2) AS ESTOQUE_IDEAL,
    CASE
        WHEN B.QTD_VENDIDA_PERIODO = 0 AND B.QTD_ESTOQUE_ATUAL > 0 THEN 'EXCESSO'
        WHEN B.QTD_VENDIDA_PERIODO = 0 AND B.QTD_ESTOQUE_ATUAL = 0 THEN 'SEM GIRO'
        WHEN (B.QTD_ESTOQUE_ATUAL / NULLIF((B.QTD_VENDIDA_PERIODO / PR.DIAS_JANELA_VENDA), 0)) < PR.DIAS_CRITICO THEN 'CRITICO'
        WHEN (B.QTD_ESTOQUE_ATUAL / NULLIF((B.QTD_VENDIDA_PERIODO / PR.DIAS_JANELA_VENDA), 0)) < PR.DIAS_ALERTA THEN 'ALERTA'
        WHEN (B.QTD_ESTOQUE_ATUAL / NULLIF((B.QTD_VENDIDA_PERIODO / PR.DIAS_JANELA_VENDA), 0)) >= PR.DIAS_EXCESSO THEN 'EXCESSO'
        ELSE 'ESTAVEL'
    END AS STATUS_COBERTURA,
    CASE
        WHEN B.QTD_VENDIDA_PERIODO = 0 AND B.QTD_ESTOQUE_ATUAL > 0 THEN 'Produtos para Promocao'
        WHEN B.QTD_ESTOQUE_ATUAL <= 0 THEN 'Produtos para Reposicao'
        WHEN (B.QTD_ESTOQUE_ATUAL / NULLIF((B.QTD_VENDIDA_PERIODO / PR.DIAS_JANELA_VENDA), 0)) < PR.DIAS_CRITICO THEN 'Produtos para Reposicao'
        WHEN (CASE WHEN B.ULTIMA_VENDA IS NULL THEN 9999 ELSE CURRENT_DATE - B.ULTIMA_VENDA END) >= PR.DIAS_SEM_VENDA_ALERTA
             AND B.QTD_ESTOQUE_ATUAL > 0 THEN 'Produtos Parados'
        ELSE 'Estavel'
    END AS CATEGORIA_ACAO,
    CASE
        WHEN ROUND((B.QTD_VENDIDA_PERIODO / PR.DIAS_JANELA_VENDA) * PR.DIAS_ALERTA * (1 + PR.FATOR_ESTOQUE_SEG), 2) > B.QTD_ESTOQUE_ATUAL
        THEN ROUND(((B.QTD_VENDIDA_PERIODO / PR.DIAS_JANELA_VENDA) * PR.DIAS_ALERTA * (1 + PR.FATOR_ESTOQUE_SEG)) - B.QTD_ESTOQUE_ATUAL, 0)
        ELSE 0
    END AS SUGESTAO_COMPRA_QTD,
    CASE
        WHEN B.VALOR_VENDAS_PERIODO > 0
        THEN ROUND(((B.VALOR_VENDAS_PERIODO - B.CMV_ESTIMADO_PERIODO) / B.VALOR_VENDAS_PERIODO) * 100.0, 2)
        ELSE NULL
    END AS MARGEM_BRUTA_PCT,
    ROUND(B.VALOR_VENDAS_PERIODO - B.CMV_ESTIMADO_PERIODO, 2) AS MARGEM_BRUTA_RS,
    CASE
        WHEN B.CMV_ESTIMADO_PERIODO > 0
        THEN ROUND(((B.VALOR_VENDAS_PERIODO - B.CMV_ESTIMADO_PERIODO) / B.CMV_ESTIMADO_PERIODO) * 100.0, 2)
        ELSE NULL
    END AS MARKUP_PCT,
    CASE
        WHEN B.VALOR_VENDAS_PERIODO <= 0 THEN 'SEM VENDA'
        WHEN ((B.VALOR_VENDAS_PERIODO - B.CMV_ESTIMADO_PERIODO) / B.VALOR_VENDAS_PERIODO) * 100.0 < 20 THEN '< 20%'
        WHEN ((B.VALOR_VENDAS_PERIODO - B.CMV_ESTIMADO_PERIODO) / B.VALOR_VENDAS_PERIODO) * 100.0 < 40 THEN '20% - 40%'
        WHEN ((B.VALOR_VENDAS_PERIODO - B.CMV_ESTIMADO_PERIODO) / B.VALOR_VENDAS_PERIODO) * 100.0 < 60 THEN '40% - 60%'
        ELSE '>= 60%'
    END AS FAIXA_MARGEM,
    CASE
        WHEN B.VALOR_VENDAS_PERIODO > 0
        THEN ROUND(((B.VALOR_VENDAS_PERIODO - B.CMV_ESTIMADO_PERIODO) / B.VALOR_VENDAS_PERIODO) * 100.0, 2)
        ELSE NULL
    END AS "MARGEM BRUTA PRATICA"
FROM BASE B
CROSS JOIN PARAMS PR
ORDER BY
    CATEGORIA_ACAO,
    STATUS_COBERTURA,
    DIAS_SEM_VENDA DESC,
    ESTOQUE_EM_DIAS;
