SELECT TRIM(RF.RDB$RELATION_NAME) AS TABELA, TRIM(RF.RDB$FIELD_NAME) AS COLUNA
FROM RDB$RELATION_FIELDS RF
WHERE RF.RDB$RELATION_NAME IN ('TB_CTAPAG_BAIXA', 'TB_CTAPAG_BAIXA_MOVTO')
ORDER BY TABELA, RF.RDB$FIELD_POSITION
