SELECT TRIM(RF.RDB$RELATION_NAME) AS TABELA, TRIM(RF.RDB$FIELD_NAME) AS COLUNA
FROM RDB$RELATION_FIELDS RF
WHERE RF.RDB$RELATION_NAME IN ('TB_PLANOS_PLG', 'TB_PLANOS_PLG_ITEM', 'TB_PLANOS_PLG_SUBITEM')
ORDER BY TABELA, RF.RDB$FIELD_POSITION
