SELECT TRIM(RF.RDB$RELATION_NAME) AS TABELA, TRIM(RF.RDB$FIELD_NAME) AS COLUNA
FROM RDB$RELATION_FIELDS RF
WHERE RF.RDB$RELATION_NAME IN ('TB_MOVDIARIO', 'TB_BANCO_CTA_MOVTO')
ORDER BY TABELA, RF.RDB$FIELD_POSITION
