-- Contas a receber por cliente (TB_CONTA_RECEBER + TB_CLIENTE; sufixo _2 opcional via API)
-- Saldo em aberto (VLR_RESTANTE), títulos não cancelados.
-- Prazo médio emissão→vencimento e PMR vencimento→última baixa (quando existir).
-- LIBERADO / LIMITE_CREDITO: placeholders NULL — mapeie colunas reais de TB_CLIENTE se existirem.

SELECT
    C.ID_CLIENTE,
    TRIM(C.NOME) AS CLIENTE,
    COUNT(R.ID_CTAREC) AS QTD_TITULOS,
    SUM(R.VLR_CTAREC) AS VALOR_TOTAL,
    SUM(R.VLR_CTAREC) AS VALOR_TITULO,
    SUM(R.VLR_PAGO) AS VALOR_PAGO,
    SUM(R.VLR_RESTANTE) AS SALDO_ABERTO,
    SUM(R.VLR_RESTANTE) AS VALOR_RESTANTE,
    MIN(R.DT_VENCTO) AS PRIMEIRO_VENCTO,
    MAX(R.DT_VENCTO) AS ULTIMO_VENCTO,
    ROUND(AVG(CAST(R.DT_VENCTO - R.DT_EMISSAO AS DOUBLE PRECISION)), 2) AS PRAZO_MEDIO_EMISSAO_VENC_DIAS,
    ROUND(AVG(CASE WHEN BX.DT_ULTIMA_BAIXA IS NOT NULL
        THEN CAST(BX.DT_ULTIMA_BAIXA - R.DT_VENCTO AS DOUBLE PRECISION) END), 2) AS PMR_DIAS_VENCIMENTO_ATE_BAIXA,
    CAST(NULL AS VARCHAR(5)) AS LIBERADO,
    CAST(NULL AS DOUBLE PRECISION) AS LIMITE_CREDITO
FROM TB_CLIENTE C
INNER JOIN TB_CONTA_RECEBER R ON R.ID_CLIENTE = C.ID_CLIENTE
    AND (R.CANC IS NULL OR TRIM(R.CANC) = '' OR R.CANC = 'N')
    AND R.VLR_RESTANTE > 0
LEFT JOIN (
    SELECT ID_CTAREC, MAX(DT_BAIXA) AS DT_ULTIMA_BAIXA
    FROM TB_CTAREC_BAIXA
    GROUP BY ID_CTAREC
) BX ON BX.ID_CTAREC = R.ID_CTAREC
GROUP BY C.ID_CLIENTE, C.NOME
ORDER BY SALDO_ABERTO DESC
