-- Contas a pagar analítico: título a título por fornecedor
-- Cada linha = um título. Saldo = valor do título menos baixas (pagamentos).
-- Para só títulos em aberto: adicione no final AND (P.VLR_CTAPAG - COALESCE(B.VLR_PAGO_TOTAL, 0)) > 0

SELECT
    F.ID_FORNEC,
    TRIM(F.NOME) AS FORNECEDOR,
    P.ID_CTAPAG,
    P.DOCUMENTO,
    TRIM(P.HISTORICO) AS HISTORICO,
    P.DT_EMISSAO,
    P.DT_VENCTO,
    (P.DT_VENCTO - P.DT_EMISSAO) AS DIAS_PRAZO,
    P.VLR_CTAPAG AS VALOR_TITULO,
    COALESCE(B.VLR_PAGO_TOTAL, 0) AS VALOR_PAGO,
    P.VLR_CTAPAG - COALESCE(B.VLR_PAGO_TOTAL, 0) AS SALDO_ABERTO
FROM TB_CONTA_PAGAR P
INNER JOIN TB_FORNECEDOR F ON F.ID_FORNEC = P.ID_FORNEC
LEFT JOIN (
    SELECT ID_CTAPAG,
           SUM(VLR_PAGO) AS VLR_PAGO_TOTAL
    FROM TB_CTAPAG_BAIXA
    GROUP BY ID_CTAPAG
) B ON B.ID_CTAPAG = P.ID_CTAPAG
ORDER BY F.NOME, P.DT_VENCTO
