-- Posição de saldos bancários/caixa na data corrente (TB_BANCO_CTA).
-- SALDO_DISPONIVEL: SD_REAL — saldo líquido / disponível conforme cadastro de movimentos.
-- SALDO_CONCILIADO: SD_BANCO — saldo na última conciliação com extrato (quando informado).
-- SALDO_TALAO_CONTABIL: SD_TALAO — saldo contábil / em livro (referência).
SELECT
  C.ID_CONTA,
  TRIM(C.DESCRICAO) AS DESCRICAO,
  TRIM(B.NOME) AS BANCO,
  TRIM(C.AGENCIA) AS AGENCIA,
  TRIM(C.CONTA) AS CONTA_CORRENTE,
  TRIM(C.STATUS) AS STATUS,
  TRIM(C.TIPOCONTA) AS TIPO_CONTA,
  COALESCE(C.SD_REAL, 0) AS SALDO_DISPONIVEL,
  COALESCE(C.SD_BANCO, 0) AS SALDO_CONCILIADO,
  COALESCE(C.SD_TALAO, 0) AS SALDO_TALAO_CONTABIL,
  C.DT_ULTCONC AS DATA_ULTIMA_CONCILIACAO
FROM TB_BANCO_CTA C
LEFT JOIN TB_BANCO_SIS B ON B.ID_BANCO = C.ID_BANCO
