-- Contas a pagar: grão título, hierarquia por data de vencimento
-- (ano/mês → semana do mês 1–7, 8–14… → dia → fornecedor → documento).
--
-- Regra de negócio (Construneves): não há pagamento parcial — se existir
-- qualquer valor baixado em TB_CTAPAG_BAIXA, o título é tratado como
-- totalmente liquidado (SALDO_ABERTO = 0) e não entra nesta matriz de “em aberto”.

SELECT
    CAST(EXTRACT(YEAR FROM P.DT_VENCTO) AS INTEGER) AS ANO,
    CAST(EXTRACT(MONTH FROM P.DT_VENCTO) AS INTEGER) AS MES_NUM,
    CASE
        WHEN EXTRACT(DAY FROM P.DT_VENCTO) BETWEEN 1 AND 7 THEN 1
        WHEN EXTRACT(DAY FROM P.DT_VENCTO) BETWEEN 8 AND 14 THEN 2
        WHEN EXTRACT(DAY FROM P.DT_VENCTO) BETWEEN 15 AND 21 THEN 3
        WHEN EXTRACT(DAY FROM P.DT_VENCTO) BETWEEN 22 AND 28 THEN 4
        ELSE 5
    END AS SEMANA_MES,
    CAST(EXTRACT(DAY FROM P.DT_VENCTO) AS INTEGER) AS DIA_MES,
    P.ID_FORNEC,
    TRIM(F.NOME) AS FORNECEDOR,
    P.ID_CTAPAG,
    TRIM(P.DOCUMENTO) AS DOCUMENTO,
    P.VLR_CTAPAG AS VALOR_TITULO,
    CASE
        WHEN COALESCE(B.VLR_PAGO_TOTAL, 0) > 0.005 THEN 0
        ELSE P.VLR_CTAPAG
    END AS SALDO_ABERTO,
    CASE
        WHEN COALESCE(B.VLR_PAGO_TOTAL, 0) > 0.005 THEN 0
        WHEN P.DT_VENCTO >= CURRENT_DATE THEN P.VLR_CTAPAG
        ELSE 0
    END AS VALOR_A_VENCER,
    P.DT_VENCTO
FROM TB_CONTA_PAGAR P
INNER JOIN TB_FORNECEDOR F ON F.ID_FORNEC = P.ID_FORNEC
LEFT JOIN (
    SELECT ID_CTAPAG, SUM(VLR_PAGO) AS VLR_PAGO_TOTAL
    FROM TB_CTAPAG_BAIXA
    GROUP BY ID_CTAPAG
) B ON B.ID_CTAPAG = P.ID_CTAPAG
WHERE P.VLR_CTAPAG > 0.005
  AND COALESCE(B.VLR_PAGO_TOTAL, 0) <= 0.005
ORDER BY P.DT_VENCTO, F.NOME, P.DOCUMENTO
