-- Recebimentos analíticos: uma linha por baixa (TB_CTAREC_BAIXA).
-- Complementa contas_receber_analitico_macro_micro.sql para "Valor recebido por data".

SELECT
    CAST(CURRENT_DATE AS DATE) AS REF_DATA_RELATORIO,
    C.ID_CLIENTE,
    TRIM(C.NOME) AS CLIENTE,
    R.ID_CTAREC,
    TRIM(R.DOCUMENTO) AS DOCUMENTO,
    B.ID_BAIXA,
    B.DT_BAIXA AS DATA_BAIXA,
    B.VLR_RECEB AS VALOR_RECEBIDO,
    COALESCE(B.VLR_DESC, 0) AS VALOR_DESCONTO_BAIXA,
    COALESCE(B.VLR_JURO, 0) AS VALOR_JUROS_BAIXA,
    TRIM(COALESCE(PT.DESCRICAO, '')) AS PORTADOR
FROM TB_CTAREC_BAIXA B
INNER JOIN TB_CONTA_RECEBER R ON R.ID_CTAREC = B.ID_CTAREC
INNER JOIN TB_CLIENTE C ON C.ID_CLIENTE = R.ID_CLIENTE
LEFT JOIN TB_CONTA_PORTADOR PT ON PT.ID_PORTADOR = R.ID_PORTADOR
WHERE (R.CANC IS NULL OR TRIM(R.CANC) = '' OR R.CANC = 'N')
ORDER BY B.DT_BAIXA DESC, C.NOME, R.ID_CTAREC
