-- Analítico: título a título por cliente + prazo médio de recebimento do cliente
-- Cada linha = um título em aberto. PRAZO_MEDIO = média dos prazos (emissão → vencimento) do cliente.

SELECT
    C.ID_CLIENTE,
    TRIM(C.NOME) AS CLIENTE,
    R.ID_CTAREC,
    R.DOCUMENTO,
    TRIM(R.HISTORICO) AS HISTORICO,
    R.DT_EMISSAO,
    R.DT_VENCTO,
    (R.DT_VENCTO - R.DT_EMISSAO) AS DIAS_PRAZO,
    R.VLR_CTAREC AS VALOR_TITULO,
    R.VLR_PAGO,
    R.VLR_RESTANTE AS SALDO_ABERTO,
    ROUND(PM.PRAZO_MEDIO_DIAS, 0) AS PRAZO_MEDIO_RECEBIMENTO_DIAS
FROM TB_CLIENTE C
INNER JOIN TB_CONTA_RECEBER R ON R.ID_CLIENTE = C.ID_CLIENTE
    AND (R.CANC IS NULL OR TRIM(R.CANC) = '' OR R.CANC = 'N')
    AND R.VLR_RESTANTE > 0
INNER JOIN (
    SELECT ID_CLIENTE,
           AVG(CAST(R2.DT_VENCTO - R2.DT_EMISSAO AS DOUBLE PRECISION)) AS PRAZO_MEDIO_DIAS
    FROM TB_CONTA_RECEBER R2
    WHERE (R2.CANC IS NULL OR TRIM(R2.CANC) = '' OR R2.CANC = 'N')
      AND R2.VLR_RESTANTE > 0
    GROUP BY R2.ID_CLIENTE
) PM ON PM.ID_CLIENTE = R.ID_CLIENTE
ORDER BY C.NOME, R.DT_VENCTO
