-- Rode este SQL para descobrir o nome correto da coluna de estoque
-- na TB_EST_IDENTIFICADOR_2.

SELECT
    TRIM(RF.RDB$FIELD_NAME) AS COLUNA
FROM RDB$RELATION_FIELDS RF
WHERE RF.RDB$RELATION_NAME = 'TB_EST_IDENTIFICADOR_2'
ORDER BY RF.RDB$FIELD_POSITION;
