-- DRE Detalhada (CLIPP) a partir do movimento diário e plano de contas
-- Contas de resultado: 4 (receita/custo), 5 (despesas), 6 (resultado financeiro), 7 (retiradas)
-- Valor = Créditos - Débitos (receita fica positivo, custo/despesa negativo)
-- Para filtrar por período: descomente e ajuste as datas no WHERE de MOV.

WITH MOV AS (
    SELECT
        M.ID_CTAPLA,
        SUM(CASE WHEN M.TIP_MOVTO = 'C' THEN M.VLR_MOVTO ELSE -M.VLR_MOVTO END) AS VALOR
    FROM TB_MOVDIARIO M
    WHERE M.ID_CTAPLA IN (
        SELECT P.ID_CTAPLA FROM TB_PLANO_CONTAS P
        WHERE (P.COD_CONTA STARTING WITH '4' OR P.COD_CONTA STARTING WITH '5'
               OR P.COD_CONTA STARTING WITH '6' OR P.COD_CONTA STARTING WITH '7')
    )
    /* Período (exemplo: jan/2026): */
    /* AND M.DT_MOVTO >= '2026-01-01' AND M.DT_MOVTO < '2026-02-01' */
    GROUP BY M.ID_CTAPLA
),
CONTAS_DRE AS (
    SELECT
        P.ID_CTAPLA,
        P.COD_CONTA,
        TRIM(P.DESCRICAO) AS DESCRICAO,
        P.COD_PAI,
        CASE
            WHEN P.COD_CONTA STARTING WITH '4.01.01.01' THEN 1
            WHEN P.COD_CONTA STARTING WITH '4.01.01.03' OR P.COD_CONTA = '4.01.01.03.1' THEN 2
            WHEN P.COD_CONTA = '4.01.01.1' OR P.COD_CONTA = '4.01.01' OR P.COD_CONTA = '4.01' THEN 3
            WHEN P.COD_CONTA STARTING WITH '4.01.03' OR P.COD_CONTA = '4.01.03.1' THEN 4
            WHEN P.COD_CONTA STARTING WITH '4.01.05' THEN 5
            WHEN P.COD_CONTA = '4.01.1' THEN 6
            WHEN P.COD_CONTA STARTING WITH '4.1' OR P.COD_CONTA STARTING WITH '4.3' OR P.COD_CONTA STARTING WITH '4.4'
                 OR P.COD_CONTA STARTING WITH '4.5' OR P.COD_CONTA STARTING WITH '4.6' OR P.COD_CONTA STARTING WITH '4.7'
                 OR P.COD_CONTA STARTING WITH '4.8' THEN 7
            WHEN P.COD_CONTA STARTING WITH '5' THEN 8
            WHEN P.COD_CONTA STARTING WITH '6' THEN 9
            WHEN P.COD_CONTA STARTING WITH '7' THEN 10
            ELSE 0
        END AS ORDEM_DRE,
        CASE
            WHEN P.COD_CONTA STARTING WITH '4.01.01.01' OR P.COD_CONTA = '4.01.01.01.1' THEN '1.RECEITA BRUTA'
            WHEN P.COD_CONTA STARTING WITH '4.01.01.03' OR P.COD_CONTA = '4.01.01.03.1' THEN '2.DEDUCOES'
            WHEN P.COD_CONTA = '4.01.01.1' OR P.COD_CONTA = '4.01.01' OR P.COD_CONTA = '4.01' THEN '3.RECEITA BRUTA (TOTAL)'
            WHEN P.COD_CONTA STARTING WITH '4.01.03' OR P.COD_CONTA = '4.01.03.1' THEN '4.CUSTO BENS/SERVICOS'
            WHEN P.COD_CONTA STARTING WITH '4.01.05' THEN '5.OUTRAS RECEITAS OPERAC.'
            WHEN P.COD_CONTA = '4.01.1' THEN '6.RECEITA LIQUIDA'
            WHEN P.COD_CONTA STARTING WITH '4.1' OR P.COD_CONTA STARTING WITH '4.3' OR P.COD_CONTA STARTING WITH '4.4'
                 OR P.COD_CONTA STARTING WITH '4.5' OR P.COD_CONTA STARTING WITH '4.6' OR P.COD_CONTA STARTING WITH '4.7'
                 OR P.COD_CONTA STARTING WITH '4.8' THEN '7.CUSTOS OPERACIONAIS'
            WHEN P.COD_CONTA STARTING WITH '5' THEN '8.DESPESAS'
            WHEN P.COD_CONTA STARTING WITH '6' THEN '9.RESULTADO FINANCEIRO'
            WHEN P.COD_CONTA STARTING WITH '7' THEN '10.RETIRADAS/DIRETORIA'
            ELSE 'OUTROS'
        END AS BLOCO_DRE
    FROM TB_PLANO_CONTAS P
    WHERE (P.COD_CONTA STARTING WITH '4' OR P.COD_CONTA STARTING WITH '5'
           OR P.COD_CONTA STARTING WITH '6' OR P.COD_CONTA STARTING WITH '7')
)
SELECT
    C.COD_CONTA,
    C.DESCRICAO,
    C.BLOCO_DRE,
    C.ORDEM_DRE,
    COALESCE(M.VALOR, 0) AS VALOR_PERIODO
FROM CONTAS_DRE C
LEFT JOIN MOV M ON M.ID_CTAPLA = C.ID_CTAPLA
ORDER BY C.ORDEM_DRE, C.COD_CONTA
