-- Totais por bloco DRE no mês corrente (lançamentos até hoje).
WITH LANCS AS (
    SELECT
        CASE
            WHEN P.COD_CONTA STARTING WITH '4.01.01.01' OR P.COD_CONTA = '4.01.01.01.1' THEN '1.RECEITA BRUTA'
            WHEN P.COD_CONTA STARTING WITH '4.01.01.03' OR P.COD_CONTA = '4.01.01.03.1' THEN '2.DEDUCOES'
            WHEN P.COD_CONTA = '4.01.01.1' OR P.COD_CONTA = '4.01.01' OR P.COD_CONTA = '4.01' THEN '3.RECEITA BRUTA (TOTAL)'
            WHEN P.COD_CONTA STARTING WITH '4.01.03' OR P.COD_CONTA = '4.01.03.1' THEN '4.CUSTO BENS/SERVICOS'
            WHEN P.COD_CONTA STARTING WITH '4.01.05' THEN '5.OUTRAS RECEITAS OPERAC.'
            WHEN P.COD_CONTA = '4.01.1' THEN '6.RECEITA LIQUIDA'
            WHEN P.COD_CONTA STARTING WITH '4.1' OR P.COD_CONTA STARTING WITH '4.3' OR P.COD_CONTA STARTING WITH '4.4'
                 OR P.COD_CONTA STARTING WITH '4.5' OR P.COD_CONTA STARTING WITH '4.6' OR P.COD_CONTA STARTING WITH '4.7'
                 OR P.COD_CONTA STARTING WITH '4.8' THEN '7.CUSTOS OPERACIONAIS'
            WHEN P.COD_CONTA STARTING WITH '5' THEN '8.DESPESAS'
            WHEN P.COD_CONTA STARTING WITH '6' THEN '9.RESULTADO FINANCEIRO'
            WHEN P.COD_CONTA STARTING WITH '7' THEN '10.RETIRADAS/DIRETORIA'
            ELSE 'OUTROS'
        END AS BLOCO_DRE,
        CASE WHEN M.TIP_MOVTO = 'C' THEN M.VLR_MOVTO ELSE -M.VLR_MOVTO END AS VALOR_DRE
    FROM TB_MOVDIARIO M
    INNER JOIN TB_PLANO_CONTAS P ON P.ID_CTAPLA = M.ID_CTAPLA
    WHERE (P.COD_CONTA STARTING WITH '4' OR P.COD_CONTA STARTING WITH '5'
           OR P.COD_CONTA STARTING WITH '6' OR P.COD_CONTA STARTING WITH '7')
      AND M.DT_MOVTO >= CURRENT_DATE - (EXTRACT(DAY FROM CURRENT_DATE) - 1)
      AND M.DT_MOVTO <= CURRENT_DATE
)
SELECT
    BLOCO_DRE,
    ROUND(COALESCE(SUM(VALOR_DRE), 0), 2) AS TOTAL
FROM LANCS
WHERE BLOCO_DRE <> 'OUTROS'
GROUP BY BLOCO_DRE
ORDER BY BLOCO_DRE
