-- Fragmento BCG + BCG_ROWS (sem SELECT final). Concatenado em Python.
-- Alinhado a matriz_bcg_produtos_2.sql

WITH
PARAMS AS (
    SELECT
        90 AS DIAS_JANELA,
        10.0 AS LIMIAR_CRESCIMENTO_PCT,
        10.0 AS LIMIAR_PARTICIPACAO_PCT
    FROM RDB$DATABASE
),
VENDAS_FILTRADAS AS (
    SELECT
        N.ID_NFVENDA,
        N.DT_SAIDA
    FROM TB_NFVENDA_2 N
    CROSS JOIN PARAMS PR
    WHERE COALESCE(N.STATUS, '') <> 'C'
      AND N.DT_SAIDA >= CURRENT_DATE - (PR.DIAS_JANELA * 2)
      AND N.DT_SAIDA < CURRENT_DATE
),
VENDAS_BASE AS (
    SELECT
        I.ID_IDENTIFICADOR,
        VF.DT_SAIDA AS DATA_VENDA,
        COALESCE(I.VLR_TOTAL, 0) AS VALOR,
        COALESCE(I.VLR_CUSTO, 0) AS CUSTO
    FROM TB_NFV_ITEM_2 I
    INNER JOIN VENDAS_FILTRADAS VF ON VF.ID_NFVENDA = I.ID_NFVENDA
),
VENDAS_PERIODO AS (
    SELECT
        V.ID_IDENTIFICADOR,
        SUM(CASE
            WHEN V.DATA_VENDA >= CURRENT_DATE - PR.DIAS_JANELA
             AND V.DATA_VENDA < CURRENT_DATE
            THEN V.VALOR ELSE 0 END) AS VALOR_ATUAL,
        SUM(CASE
            WHEN V.DATA_VENDA >= CURRENT_DATE - (PR.DIAS_JANELA * 2)
             AND V.DATA_VENDA < CURRENT_DATE - PR.DIAS_JANELA
            THEN V.VALOR ELSE 0 END) AS VALOR_ANTERIOR,
        SUM(CASE
            WHEN V.DATA_VENDA >= CURRENT_DATE - PR.DIAS_JANELA
             AND V.DATA_VENDA < CURRENT_DATE
            THEN V.CUSTO ELSE 0 END) AS CUSTO_ATUAL
    FROM VENDAS_BASE V
    CROSS JOIN PARAMS PR
    GROUP BY V.ID_IDENTIFICADOR
),
BASE AS (
    SELECT
        P.ID_IDENTIFICADOR,
        TRIM(COALESCE(E.DESCRICAO, '(sem descricao)')) AS PRODUTO,
        TRIM(COALESCE(P.REFERENCIA, '')) AS REFERENCIA,
        COALESCE(P.ID_NIVEL2, P.ID_NIVEL1, E.ID_GRUPO) AS ID_CLASSIFICACAO,
        COALESCE(VP.VALOR_ATUAL, 0) AS VALOR_ATUAL,
        COALESCE(VP.VALOR_ANTERIOR, 0) AS VALOR_ANTERIOR,
        COALESCE(VP.CUSTO_ATUAL, 0) AS CUSTO_ATUAL
    FROM TB_EST_PRODUTO_2 P
    INNER JOIN TB_EST_IDENTIFICADOR_2 I ON I.ID_IDENTIFICADOR = P.ID_IDENTIFICADOR
    INNER JOIN TB_ESTOQUE_2 E ON E.ID_ESTOQUE = I.ID_ESTOQUE
    LEFT JOIN VENDAS_PERIODO VP ON VP.ID_IDENTIFICADOR = P.ID_IDENTIFICADOR
),
CLASSIF_TOTAIS AS (
    SELECT
        B.ID_CLASSIFICACAO,
        SUM(B.VALOR_ATUAL) AS VALOR_CLASSIFICACAO_ATUAL
    FROM BASE B
    WHERE B.VALOR_ATUAL > 0 OR B.VALOR_ANTERIOR > 0
    GROUP BY B.ID_CLASSIFICACAO
),
BCG_ROWS AS (
    SELECT
        B.ID_IDENTIFICADOR,
        B.PRODUTO,
        B.REFERENCIA,
        B.ID_CLASSIFICACAO,
        B.VALOR_ATUAL,
        B.VALOR_ANTERIOR,
        B.CUSTO_ATUAL,
        ROUND(B.VALOR_ATUAL - B.CUSTO_ATUAL, 2) AS MARGEM_BRUTA_VALOR_ATUAL,
        CASE WHEN B.VALOR_ATUAL > 0
             THEN ROUND(((B.VALOR_ATUAL - B.CUSTO_ATUAL) / B.VALOR_ATUAL) * 100.0, 2)
             ELSE NULL END AS MARGEM_BRUTA_PCT_ATUAL,
        CASE WHEN B.VALOR_ANTERIOR > 0
             THEN ROUND(((B.VALOR_ATUAL - B.VALOR_ANTERIOR) / B.VALOR_ANTERIOR) * 100.0, 2)
             WHEN B.VALOR_ATUAL > 0 THEN 100.0
             ELSE 0 END AS CRESCIMENTO_VENDAS_PCT,
        CASE WHEN COALESCE(C.VALOR_CLASSIFICACAO_ATUAL, 0) > 0
             THEN ROUND((B.VALOR_ATUAL / C.VALOR_CLASSIFICACAO_ATUAL) * 100.0, 2)
             ELSE 0 END AS PARTICIPACAO_VENDAS_CLASSIFICACAO_PCT,
        CASE
            WHEN (CASE WHEN B.VALOR_ANTERIOR > 0 THEN ((B.VALOR_ATUAL - B.VALOR_ANTERIOR) / B.VALOR_ANTERIOR) * 100.0
                       WHEN B.VALOR_ATUAL > 0 THEN 100.0 ELSE 0 END) >= PR.LIMIAR_CRESCIMENTO_PCT
             AND (CASE WHEN COALESCE(C.VALOR_CLASSIFICACAO_ATUAL, 0) > 0 THEN (B.VALOR_ATUAL / C.VALOR_CLASSIFICACAO_ATUAL) * 100.0 ELSE 0 END) >= PR.LIMIAR_PARTICIPACAO_PCT
            THEN 'ESTRELA'
            WHEN (CASE WHEN B.VALOR_ANTERIOR > 0 THEN ((B.VALOR_ATUAL - B.VALOR_ANTERIOR) / B.VALOR_ANTERIOR) * 100.0
                       WHEN B.VALOR_ATUAL > 0 THEN 100.0 ELSE 0 END) < PR.LIMIAR_CRESCIMENTO_PCT
             AND (CASE WHEN COALESCE(C.VALOR_CLASSIFICACAO_ATUAL, 0) > 0 THEN (B.VALOR_ATUAL / C.VALOR_CLASSIFICACAO_ATUAL) * 100.0 ELSE 0 END) >= PR.LIMIAR_PARTICIPACAO_PCT
            THEN 'VACA LEITEIRA'
            WHEN (CASE WHEN B.VALOR_ANTERIOR > 0 THEN ((B.VALOR_ATUAL - B.VALOR_ANTERIOR) / B.VALOR_ANTERIOR) * 100.0
                       WHEN B.VALOR_ATUAL > 0 THEN 100.0 ELSE 0 END) >= PR.LIMIAR_CRESCIMENTO_PCT
             AND (CASE WHEN COALESCE(C.VALOR_CLASSIFICACAO_ATUAL, 0) > 0 THEN (B.VALOR_ATUAL / C.VALOR_CLASSIFICACAO_ATUAL) * 100.0 ELSE 0 END) < PR.LIMIAR_PARTICIPACAO_PCT
            THEN 'PONTO INTERROGACAO'
            ELSE 'ABACAXI'
        END AS CLASSE_BCG
    FROM BASE B
    LEFT JOIN CLASSIF_TOTAIS C ON C.ID_CLASSIFICACAO = B.ID_CLASSIFICACAO
    CROSS JOIN PARAMS PR
    WHERE B.VALOR_ATUAL > 0 OR B.VALOR_ANTERIOR > 0
)
