-- Agregados BCG. Executar após estoque_bcg_fragment.sql.
SELECT
    COUNT(*) AS TOTAL_PRODUTOS,
    SUM(CASE WHEN B.CLASSE_BCG = 'ESTRELA' THEN 1 ELSE 0 END) AS QTD_ESTRELA,
    SUM(CASE WHEN B.CLASSE_BCG = 'VACA LEITEIRA' THEN 1 ELSE 0 END) AS QTD_VACA,
    SUM(CASE WHEN B.CLASSE_BCG = 'PONTO INTERROGACAO' THEN 1 ELSE 0 END) AS QTD_PONTO,
    SUM(CASE WHEN B.CLASSE_BCG = 'ABACAXI' THEN 1 ELSE 0 END) AS QTD_ABACAXI,
    ROUND(COALESCE(SUM(B.VALOR_ATUAL), 0), 2) AS SOMA_VALOR_ATUAL
FROM BCG_ROWS B
