-- Prazo médio da emissão da nota até a entrada da nota, por produto
-- Mostra quanto tempo em média leva para cada produto ser entregue (em dias)
-- Fonte: TB_NFCOMPRA + TB_NFC_ITEM + TB_EST_IDENTIFICADOR + TB_ESTOQUE (descrição)

SELECT
    P.ID_IDENTIFICADOR,
    TRIM(COALESCE(E.DESCRICAO, '(sem descrição)')) AS PRODUTO,
    TRIM(COALESCE(P.REFERENCIA, ''))               AS REFERENCIA,
    COUNT(I.ID_NFCITEM)                            AS QTD_ITENS_NOTAS,
    COUNT(DISTINCT N.ID_NFCOMPRA)                  AS QTD_NOTAS,
    ROUND(AVG(CAST(N.DT_ENTRADA - N.DT_EMISSAO AS DOUBLE PRECISION)), 1) AS PRAZO_MEDIO_DIAS,
    MIN(N.DT_ENTRADA - N.DT_EMISSAO)               AS MENOR_PRAZO_DIAS,
    MAX(N.DT_ENTRADA - N.DT_EMISSAO)              AS MAIOR_PRAZO_DIAS
FROM TB_NFC_ITEM I
INNER JOIN TB_NFCOMPRA N ON N.ID_NFCOMPRA = I.ID_NFCOMPRA
INNER JOIN TB_EST_PRODUTO P ON P.ID_IDENTIFICADOR = I.ID_IDENTIFICADOR
INNER JOIN TB_EST_IDENTIFICADOR ID ON ID.ID_IDENTIFICADOR = I.ID_IDENTIFICADOR
INNER JOIN TB_ESTOQUE E ON E.ID_ESTOQUE = ID.ID_ESTOQUE
WHERE N.DT_EMISSAO IS NOT NULL
  AND N.DT_ENTRADA IS NOT NULL
  AND N.DT_ENTRADA >= N.DT_EMISSAO
  /* Opcional: filtrar por período de entrada
  AND N.DT_ENTRADA >= '2025-01-01'
  AND N.DT_ENTRADA <  '2026-01-01'
  */
GROUP BY P.ID_IDENTIFICADOR, E.DESCRICAO, P.REFERENCIA
ORDER BY PRAZO_MEDIO_DIAS DESC
