-- Reconciliação venda: **MT** (tabelas com sufixo _2) x **CLIPP** (tabelas sem sufixo), por ID_IDENTIFICADOR.
-- MT: TB_NFVENDA_2 + TB_NFV_ITEM_2 — FIM = 'Finalizado'; VLR linha: VLR_TOTAL - VLR_DESC; período por DT_SAIDA.
-- CLIPP: TB_NFVENDA + TB_NFV_ITEM — STATUS = 'E' (efetivada; exclui 'C' cancel.); período por DT_SAIDA/DT_EMISSAO.
-- Estoque exibido: TB_EST_PRODUTO_2 (sufixo _2 = módulo MT, alinhado ao resto do painel de estoque).
-- Placeholders: __DATA_INI__ e __DATA_FIM__ (já com aspas).
WITH
MT AS (
    SELECT
        I.ID_IDENTIFICADOR,
        SUM(COALESCE(I.VLR_TOTAL, 0) - COALESCE(I.VLR_DESC, 0)) AS VLR_MT
    FROM TB_NFV_ITEM_2 I
    INNER JOIN TB_NFVENDA_2 N ON N.ID_NFVENDA = I.ID_NFVENDA
    WHERE N.FIM = 'Finalizado'
        AND COALESCE(CAST(N.DT_SAIDA AS DATE), CAST(N.DT_EMISSAO AS DATE)) BETWEEN __DATA_INI__ AND __DATA_FIM__
    GROUP BY I.ID_IDENTIFICADOR
),
CL AS (
    SELECT
        I.ID_IDENTIFICADOR,
        SUM(COALESCE(I.VLR_TOTAL, 0) - COALESCE(I.VLR_DESC, 0)) AS VLR_CLIPP
    FROM TB_NFV_ITEM I
    INNER JOIN TB_NFVENDA N ON N.ID_NFVENDA = I.ID_NFVENDA
    WHERE COALESCE(N.STATUS, 'E') = 'E'
        AND COALESCE(CAST(N.DT_SAIDA AS DATE), CAST(N.DT_EMISSAO AS DATE)) BETWEEN __DATA_INI__ AND __DATA_FIM__
    GROUP BY I.ID_IDENTIFICADOR
),
U AS (
    SELECT MT.ID_IDENTIFICADOR, MT.VLR_MT, CAST(0 AS DOUBLE PRECISION) AS VLR_CLIPP
    FROM MT
    UNION ALL
    SELECT CL.ID_IDENTIFICADOR, CAST(0 AS DOUBLE PRECISION) AS VLR_MT, CL.VLR_CLIPP
    FROM CL
),
A AS (
    SELECT
        U.ID_IDENTIFICADOR,
        SUM(U.VLR_MT) AS VLR_MT,
        SUM(U.VLR_CLIPP) AS VLR_CLIPP
    FROM U
    GROUP BY U.ID_IDENTIFICADOR
)
SELECT
    A.ID_IDENTIFICADOR,
    TRIM(COALESCE(E.DESCRICAO, '')) AS DESCRICAO,
    TRIM(COALESCE(P.REFERENCIA, '')) AS REFERENCIA,
    COALESCE(P.QTD_ATUAL, 0) AS QTD_ESTOQUE,
    A.VLR_MT,
    A.VLR_CLIPP,
    (A.VLR_MT - A.VLR_CLIPP) AS GAP_VLR,
    CASE
        WHEN ABS(A.VLR_MT) < 0.01 AND ABS(A.VLR_CLIPP) < 0.01 THEN 0.0
        WHEN ABS(A.VLR_MT) > ABS(A.VLR_CLIPP) THEN
            CASE WHEN ABS(A.VLR_MT) < 0.01 THEN NULL
            ELSE ABS(A.VLR_MT - A.VLR_CLIPP) / ABS(A.VLR_MT) END
        ELSE
            CASE WHEN ABS(A.VLR_CLIPP) < 0.01 THEN NULL
            ELSE ABS(A.VLR_MT - A.VLR_CLIPP) / ABS(A.VLR_CLIPP) END
    END AS GAP_FRAC
FROM A
INNER JOIN TB_EST_PRODUTO_2 P ON P.ID_IDENTIFICADOR = A.ID_IDENTIFICADOR
INNER JOIN TB_EST_IDENTIFICADOR_2 ID ON ID.ID_IDENTIFICADOR = A.ID_IDENTIFICADOR
INNER JOIN TB_ESTOQUE_2 E ON E.ID_ESTOQUE = ID.ID_ESTOQUE
WHERE (ABS(A.VLR_MT) + ABS(A.VLR_CLIPP)) > 0.0005
ORDER BY ABS(A.VLR_MT - A.VLR_CLIPP) DESC
