-- Agregados para GET /dash/resumo-diario (uma linha).
-- Baixas a pagar: TB_CTAPAG_BAIXA.
-- Resumo do dia no CLIPP («Pagas»): só TIP_PAGTO = 'T' → PAGAR_HOJE / PAGAR_DIA_MES_ANT.
-- Resumo do Mês («Pagas»): TIP_PAGTO IN ('T','P') no mês calendário → PAGAR_MES_CAL;
-- o mesmo IN para PAGAR_MTD / PAGAR_MTD_MES_ANT (totais do mês em curso / homólogo).
-- Baixas a receber: TB_CTAREC_BAIXA + TB_CONTA_RECEBER (sufixo _2 opcional via API).
-- Recebimentos: soma VLR_RECEB por data da baixa (DT_BAIXA), com join ao título.
-- RECEBER_MTD: do dia 1 até CURRENT_DATE (acompanhamento real).
-- RECEBER_MES_CAL: do dia 1 ao último dia do mês corrente (inclui baixas já lançadas
-- com DT_BAIXA futura no mês) — alinha ao resumo de recebidas no sistema.
-- Vendas: NF finalizada (FIM) por DT_SAIDA. Por NF: soma de VLR_PAGTO em
-- V_NFVENDA_PAGAMENTOS quando houver linhas; senão TB_NFVENDA_2.VLR_TOTALNOTAJUROS
-- (há bases em que a view de pagamentos não liga a todas as NFs e o INNER JOIN
-- zerava o total). VENDAS_MTD: até CURRENT_DATE; VENDAS_MES_CAL: mês calendário.
-- PAGAR_/VENDAS_MTD_MES_ANT: MTD homólogo (dia 1 até o mesmo dia do mês anterior).

SELECT
    (SELECT COALESCE(SUM(BX.VLR_PAGO), 0)
     FROM TB_CTAPAG_BAIXA BX
     WHERE BX.TIP_PAGTO = 'T'
       AND CAST(BX.DT_BAIXA AS DATE) = CURRENT_DATE) AS PAGAR_HOJE,
    (SELECT COALESCE(SUM(BX.VLR_PAGO), 0)
     FROM TB_CTAPAG_BAIXA BX
     WHERE BX.TIP_PAGTO IN ('T', 'P')
       AND CAST(BX.DT_BAIXA AS DATE) >= DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE)
       AND CAST(BX.DT_BAIXA AS DATE) <= CURRENT_DATE) AS PAGAR_MTD,
    (SELECT COALESCE(SUM(BX.VLR_PAGO), 0)
     FROM TB_CTAPAG_BAIXA BX
     WHERE BX.TIP_PAGTO = 'T'
       AND CAST(BX.DT_BAIXA AS DATE) = DATEADD(MONTH, -1, CURRENT_DATE)) AS PAGAR_DIA_MES_ANT,
    (SELECT COALESCE(SUM(BX.VLR_PAGO), 0)
     FROM TB_CTAPAG_BAIXA BX
     WHERE BX.TIP_PAGTO IN ('T', 'P')
       AND CAST(BX.DT_BAIXA AS DATE) >= DATEADD(MONTH, -1, DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE))
       AND CAST(BX.DT_BAIXA AS DATE) <= DATEADD(MONTH, -1, CURRENT_DATE)) AS PAGAR_MTD_MES_ANT,
    (SELECT COALESCE(SUM(BX.VLR_PAGO), 0)
     FROM TB_CTAPAG_BAIXA BX
     WHERE BX.TIP_PAGTO IN ('T', 'P')
       AND CAST(BX.DT_BAIXA AS DATE) >= DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE)
       AND CAST(BX.DT_BAIXA AS DATE) < DATEADD(MONTH, 1, DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE))) AS PAGAR_MES_CAL,
    (SELECT COALESCE(SUM(BX.VLR_PAGO), 0)
     FROM TB_CTAPAG_BAIXA BX
     WHERE BX.TIP_PAGTO IN ('T', 'P')
       AND CAST(BX.DT_BAIXA AS DATE) >= DATEADD(MONTH, -1, DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE))
       AND CAST(BX.DT_BAIXA AS DATE) < DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE)) AS PAGAR_MES_ANT_CAL,

    (SELECT COALESCE(SUM(COALESCE(B.VLR_RECEB, 0)), 0)
     FROM TB_CTAREC_BAIXA B
     INNER JOIN TB_CONTA_RECEBER R ON R.ID_CTAREC = B.ID_CTAREC
     WHERE CAST(B.DT_BAIXA AS DATE) = CURRENT_DATE) AS RECEBER_HOJE,
    (SELECT COALESCE(SUM(COALESCE(B.VLR_RECEB, 0)), 0)
     FROM TB_CTAREC_BAIXA B
     INNER JOIN TB_CONTA_RECEBER R ON R.ID_CTAREC = B.ID_CTAREC
     WHERE CAST(B.DT_BAIXA AS DATE) >= DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE)
       AND CAST(B.DT_BAIXA AS DATE) <= CURRENT_DATE) AS RECEBER_MTD,
    (SELECT COALESCE(SUM(COALESCE(B.VLR_RECEB, 0)), 0)
     FROM TB_CTAREC_BAIXA B
     INNER JOIN TB_CONTA_RECEBER R ON R.ID_CTAREC = B.ID_CTAREC
     WHERE CAST(B.DT_BAIXA AS DATE) = DATEADD(MONTH, -1, CURRENT_DATE)) AS RECEBER_DIA_MES_ANT,
    (SELECT COALESCE(SUM(COALESCE(B.VLR_RECEB, 0)), 0)
     FROM TB_CTAREC_BAIXA B
     INNER JOIN TB_CONTA_RECEBER R ON R.ID_CTAREC = B.ID_CTAREC
     WHERE CAST(B.DT_BAIXA AS DATE) >= DATEADD(MONTH, -1, DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE))
       AND CAST(B.DT_BAIXA AS DATE) <= DATEADD(MONTH, -1, CURRENT_DATE)) AS RECEBER_MTD_MES_ANT,
    (SELECT COALESCE(SUM(COALESCE(B.VLR_RECEB, 0)), 0)
     FROM TB_CTAREC_BAIXA B
     INNER JOIN TB_CONTA_RECEBER R ON R.ID_CTAREC = B.ID_CTAREC
     WHERE CAST(B.DT_BAIXA AS DATE) >= DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE)
       AND CAST(B.DT_BAIXA AS DATE) < DATEADD(MONTH, 1, DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE))) AS RECEBER_MES_CAL,
    (SELECT COALESCE(SUM(COALESCE(B.VLR_RECEB, 0)), 0)
     FROM TB_CTAREC_BAIXA B
     INNER JOIN TB_CONTA_RECEBER R ON R.ID_CTAREC = B.ID_CTAREC
     WHERE CAST(B.DT_BAIXA AS DATE) >= DATEADD(MONTH, -1, DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE))
       AND CAST(B.DT_BAIXA AS DATE) < DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE)) AS RECEBER_MES_ANT_CAL,

    (SELECT COALESCE(SUM(
        CASE
          WHEN COALESCE(PG.TOT, 0) > 0.005 THEN PG.TOT
          ELSE N.VLR_TOTALNOTAJUROS
        END
      ), 0)
     FROM TB_NFVENDA_2 N
     LEFT JOIN (SELECT P.ID_NFVENDA, COALESCE(SUM(P.VLR_PAGTO), 0) AS TOT
                FROM V_NFVENDA_PAGAMENTOS P
                GROUP BY P.ID_NFVENDA) PG ON PG.ID_NFVENDA = N.ID_NFVENDA
     WHERE N.FIM = 'Finalizado'
       AND CAST(N.DT_SAIDA AS DATE) = CURRENT_DATE) AS VENDAS_HOJE,
    (SELECT COALESCE(SUM(
        CASE
          WHEN COALESCE(PG.TOT, 0) > 0.005 THEN PG.TOT
          ELSE N.VLR_TOTALNOTAJUROS
        END
      ), 0)
     FROM TB_NFVENDA_2 N
     LEFT JOIN (SELECT P.ID_NFVENDA, COALESCE(SUM(P.VLR_PAGTO), 0) AS TOT
                FROM V_NFVENDA_PAGAMENTOS P
                GROUP BY P.ID_NFVENDA) PG ON PG.ID_NFVENDA = N.ID_NFVENDA
     WHERE N.FIM = 'Finalizado'
       AND CAST(N.DT_SAIDA AS DATE) >= DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE)
       AND CAST(N.DT_SAIDA AS DATE) <= CURRENT_DATE) AS VENDAS_MTD,
    (SELECT COALESCE(SUM(
        CASE
          WHEN COALESCE(PG.TOT, 0) > 0.005 THEN PG.TOT
          ELSE N.VLR_TOTALNOTAJUROS
        END
      ), 0)
     FROM TB_NFVENDA_2 N
     LEFT JOIN (SELECT P.ID_NFVENDA, COALESCE(SUM(P.VLR_PAGTO), 0) AS TOT
                FROM V_NFVENDA_PAGAMENTOS P
                GROUP BY P.ID_NFVENDA) PG ON PG.ID_NFVENDA = N.ID_NFVENDA
     WHERE N.FIM = 'Finalizado'
       AND CAST(N.DT_SAIDA AS DATE) = DATEADD(MONTH, -1, CURRENT_DATE)) AS VENDAS_DIA_MES_ANT,
    (SELECT COALESCE(SUM(
        CASE
          WHEN COALESCE(PG.TOT, 0) > 0.005 THEN PG.TOT
          ELSE N.VLR_TOTALNOTAJUROS
        END
      ), 0)
     FROM TB_NFVENDA_2 N
     LEFT JOIN (SELECT P.ID_NFVENDA, COALESCE(SUM(P.VLR_PAGTO), 0) AS TOT
                FROM V_NFVENDA_PAGAMENTOS P
                GROUP BY P.ID_NFVENDA) PG ON PG.ID_NFVENDA = N.ID_NFVENDA
     WHERE N.FIM = 'Finalizado'
       AND CAST(N.DT_SAIDA AS DATE) >= DATEADD(MONTH, -1, DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE))
       AND CAST(N.DT_SAIDA AS DATE) <= DATEADD(MONTH, -1, CURRENT_DATE)) AS VENDAS_MTD_MES_ANT,
    (SELECT COALESCE(SUM(
        CASE
          WHEN COALESCE(PG.TOT, 0) > 0.005 THEN PG.TOT
          ELSE N.VLR_TOTALNOTAJUROS
        END
      ), 0)
     FROM TB_NFVENDA_2 N
     LEFT JOIN (SELECT P.ID_NFVENDA, COALESCE(SUM(P.VLR_PAGTO), 0) AS TOT
                FROM V_NFVENDA_PAGAMENTOS P
                GROUP BY P.ID_NFVENDA) PG ON PG.ID_NFVENDA = N.ID_NFVENDA
     WHERE N.FIM = 'Finalizado'
       AND CAST(N.DT_SAIDA AS DATE) >= DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE)
       AND CAST(N.DT_SAIDA AS DATE) < DATEADD(MONTH, 1, DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE))) AS VENDAS_MES_CAL,
    (SELECT COALESCE(SUM(
        CASE
          WHEN COALESCE(PG.TOT, 0) > 0.005 THEN PG.TOT
          ELSE N.VLR_TOTALNOTAJUROS
        END
      ), 0)
     FROM TB_NFVENDA_2 N
     LEFT JOIN (SELECT P.ID_NFVENDA, COALESCE(SUM(P.VLR_PAGTO), 0) AS TOT
                FROM V_NFVENDA_PAGAMENTOS P
                GROUP BY P.ID_NFVENDA) PG ON PG.ID_NFVENDA = N.ID_NFVENDA
     WHERE N.FIM = 'Finalizado'
       AND CAST(N.DT_SAIDA AS DATE) >= DATEADD(MONTH, -1, DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE))
       AND CAST(N.DT_SAIDA AS DATE) < DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE)) AS VENDAS_MES_ANT_CAL
FROM RDB$DATABASE
