-- Por forma de pagamento (V_NFVENDA_PAGAMENTOS). Placeholders: __ANO__, __MES_SQL__
WITH VENDAS_NF AS (
    SELECT N.ID_NFVENDA
    FROM TB_NFVENDA_2 N
    WHERE N.FIM = 'Finalizado'
      AND CAST(EXTRACT(YEAR FROM N.DT_SAIDA) AS INTEGER) = __ANO__
      __MES_SQL__
      AND N.DT_SAIDA < CURRENT_DATE
)
SELECT
    TRIM(COALESCE(P.DESC_FORMAPAGAMENTO, '(sem descricao)')) AS FORMA_PAGAMENTO,
    COUNT(DISTINCT P.ID_NFVENDA) AS QTD_NF,
    COUNT(*) AS QTD_LINHAS_PAGTO,
    COALESCE(SUM(P.VLR_PAGTO), 0) AS TOTAL_PAGTO
FROM V_NFVENDA_PAGAMENTOS P
INNER JOIN VENDAS_NF VN ON VN.ID_NFVENDA = P.ID_NFVENDA
GROUP BY TRIM(COALESCE(P.DESC_FORMAPAGAMENTO, '(sem descricao)'))
ORDER BY COALESCE(SUM(P.VLR_PAGTO), 0) DESC
