-- CTEs VENDAS_NF + VENDAS_LINHAS. Placeholders: __ANO__, __MES_SQL__ (__MES_SQL__ vazio ou AND ... mês).
WITH VENDAS_NF AS (
    SELECT
        N.ID_NFVENDA,
        N.DT_SAIDA,
        N.ID_VENDEDOR,
        N.ID_CLIENTE,
        COALESCE(N.DESCONTO, 0) AS NF_DESCONTO
    FROM TB_NFVENDA_2 N
    WHERE N.FIM = 'Finalizado'
      AND CAST(EXTRACT(YEAR FROM N.DT_SAIDA) AS INTEGER) = __ANO__
      __MES_SQL__
      AND N.DT_SAIDA < CURRENT_DATE
),
VENDAS_LINHAS AS (
    SELECT
        VN.ID_NFVENDA,
        CAST(EXTRACT(YEAR FROM VN.DT_SAIDA) AS INTEGER) AS ANO,
        CAST(EXTRACT(MONTH FROM VN.DT_SAIDA) AS INTEGER) AS MES_NUM,
        VN.ID_VENDEDOR,
        TRIM(COALESCE(VEND.NOME, '(sem vendedor)')) AS NOME_VENDEDOR,
        VN.ID_CLIENTE,
        I.ID_IDENTIFICADOR,
        E.ID_ESTOQUE,
        TRIM(COALESCE(E.DESCRICAO, '(sem descricao)')) AS PRODUTO,
        TRIM(COALESCE(P.REFERENCIA, '')) AS REFERENCIA,
        COALESCE(E.ID_GRUPO, 0) AS ID_GRUPO,
        COALESCE(I.QTD_ITEM, 0) AS QTD_ITEM,
        COALESCE(I.VLR_TOTAL, 0) AS VLR_TOTAL,
        COALESCE(I.VLR_DESC, 0) AS VLR_DESC,
        COALESCE(I.VLR_CUSTO, 0) AS VLR_CUSTO,
        (COALESCE(I.VLR_TOTAL, 0) - COALESCE(I.VLR_DESC, 0)) AS TOTAL_LIQUIDO_LINHA,
        (COALESCE(I.VLR_TOTAL, 0) - COALESCE(I.VLR_DESC, 0) - COALESCE(I.VLR_CUSTO, 0)) AS MARGEM_BRUTA_LINHA
    FROM VENDAS_NF VN
    INNER JOIN TB_NFV_ITEM_2 I ON I.ID_NFVENDA = VN.ID_NFVENDA
    INNER JOIN TB_EST_IDENTIFICADOR_2 ID ON ID.ID_IDENTIFICADOR = I.ID_IDENTIFICADOR
    INNER JOIN TB_ESTOQUE_2 E ON E.ID_ESTOQUE = ID.ID_ESTOQUE
    INNER JOIN TB_EST_PRODUTO_2 P ON P.ID_IDENTIFICADOR = I.ID_IDENTIFICADOR
    LEFT JOIN V_FUNC_VENDEDOR VEND ON VEND.ID_FUNCIONARIO = VN.ID_VENDEDOR
)
